# Chapter 3: Calculating the similarity between documents

Continue here - I need to make a decision about whether this is in the same chapter with tf-idf or not. Probably as otherwise the end of that chapter will involve manually calculating the tf-idf for every word, as well as being a bit boring and anti-climatic.

In [1]:
# Need to find a good step-by-step tutorial of constructing the tf-idf matrix by hand
# Then I need to find another step-by-step of the cosine similarity
# I should work through both of those completely before I do the chapter!! :D
# Also, I can do the graph demonstrating the document-term similarity with the tf-idf!

In [11]:
documents = (
    "The sky is blue",
    "The sun is bright",
    "The sun in the sky is bright",
    "We can see the shining sun, the bright sun"
)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

vectorizer.fit_transform(documents)
print vectorizer.vocabulary

None


In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(documents)
print tfidf_matrix.shape

(4, 11)


In [13]:
import operator
from pprint import pprint

sorted(tfidf_vectorizer.vocabulary_.items(), key=operator.itemgetter(1))

[(u'blue', 0),
 (u'bright', 1),
 (u'can', 2),
 (u'in', 3),
 (u'is', 4),
 (u'see', 5),
 (u'shining', 6),
 (u'sky', 7),
 (u'sun', 8),
 (u'the', 9),
 (u'we', 10)]

In [16]:
print tfidf_matrix.todense()

[[ 0.65919112  0.          0.          0.          0.42075315  0.          0.
   0.51971385  0.          0.34399327  0.        ]
 [ 0.          0.52210862  0.          0.          0.52210862  0.          0.
   0.          0.52210862  0.42685801  0.        ]
 [ 0.          0.3218464   0.          0.50423458  0.3218464   0.          0.
   0.39754433  0.3218464   0.52626104  0.        ]
 [ 0.          0.23910199  0.37459947  0.          0.          0.37459947
   0.37459947  0.          0.47820398  0.39096309  0.37459947]]


In [17]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)

array([[ 1.        ,  0.36651513,  0.52305744,  0.13448867]])

In [47]:
dm = tfidf_matrix.todense()
dm

matrix([[ 0.65919112,  0.        ,  0.        ,  0.        ,  0.42075315,
          0.        ,  0.        ,  0.51971385,  0.        ,  0.34399327,
          0.        ],
        [ 0.        ,  0.52210862,  0.        ,  0.        ,  0.52210862,
          0.        ,  0.        ,  0.        ,  0.52210862,  0.42685801,
          0.        ],
        [ 0.        ,  0.3218464 ,  0.        ,  0.50423458,  0.3218464 ,
          0.        ,  0.        ,  0.39754433,  0.3218464 ,  0.52626104,
          0.        ],
        [ 0.        ,  0.23910199,  0.37459947,  0.        ,  0.        ,
          0.37459947,  0.37459947,  0.        ,  0.47820398,  0.39096309,
          0.37459947]])

Ex: Find the similarity between documents 1 and 2.  
d1 = (5, 0, 3, 0, 2, 0, 0, 2, 0, 0)  
d2 = (3, 0, 2, 0, 1, 1, 0, 1, 0, 1)  
d1 ⋅ d2 = 5*3+0*0+3*2+0*0+2*1+0*1+0*1+2*1+0*0+0*1 = 25  
||d1|| = (5*5+0*0+3*3+0*0+2*2+0*0+0*0+2*2+0*0+0*0)0.5 = (42) 0.5 = 6.481  
||d2|| = (3*3+0*0+2*2+0*0+1*1+1*1+0*0+1*1+0*0+1*1)0.5 = (17) 0.5 = 4.12  
cos(d1, d2 ) = 0.94

In [49]:
vec_dot_prod = dm.item(0, 0) * dm.item(2, 0) + dm.item(0, 1) * dm.item(2, 1) +\
               dm.item(0, 2) * dm.item(2, 2) + dm.item(0, 3) * dm.item(2, 3) +\
               dm.item(0, 4) * dm.item(2, 4) + dm.item(0, 5) * dm.item(2, 5) +\
               dm.item(0, 6) * dm.item(2, 6) + dm.item(0, 7) * dm.item(2, 7) +\
               dm.item(0, 8) * dm.item(2, 8) + dm.item(0, 9) * dm.item(2, 9) +\
               dm.item(0, 10) * dm.item(2, 10)

In [50]:
vec_dot_prod

0.5230574383703659

In [51]:
v1_sq = (dm.item(0, 0) * dm.item(0, 0) + dm.item(0, 1) * dm.item(0, 1) +\
         dm.item(0, 2) * dm.item(0, 2) + dm.item(0, 3) * dm.item(0, 3) +\
         dm.item(0, 4) * dm.item(0, 4) + dm.item(0, 5) * dm.item(0, 5) +\
         dm.item(0, 6) * dm.item(0, 6) + dm.item(0, 7) * dm.item(0, 7) +\
         dm.item(0, 8) * dm.item(0, 8) + dm.item(0, 9) * dm.item(0, 9) +\
         dm.item(0, 10) * dm.item(0, 10)) * 0.5

In [52]:
v2_sq = (dm.item(2, 0) * dm.item(2, 0) + dm.item(2, 1) * dm.item(2, 1) +\
         dm.item(2, 2) * dm.item(2, 2) + dm.item(2, 3) * dm.item(2, 3) +\
         dm.item(2, 4) * dm.item(2, 4) + dm.item(2, 5) * dm.item(2, 5) +\
         dm.item(2, 6) * dm.item(2, 6) + dm.item(2, 7) * dm.item(2, 7) +\
         dm.item(2, 8) * dm.item(2, 8) + dm.item(2, 9) * dm.item(2, 9) +\
         dm.item(2, 10) * dm.item(2, 10)) * 0.5

In [53]:
v1_sq

0.4999999999999999

In [54]:
v2_sq

0.49999999999999983

In [55]:
vec_dot_prod / v1_sq * v2_sq

0.5230574383703658

## Define the corpus

[I should put the frequencies of the original corpus here as well - this will just tie together this chapter to the previous chapter and orientate the reader to the chapter.]

Let's put together an example set, but this would also include all of the fairytales as well.

In [13]:
documents = [
    'The princess was clever',
    'The prince was handsome',
    'The prince loved the clever princess',
    '"Prince, handsome prince", said the princess',
]

## Create the index vocabulary

Index vocabulary is simply a numbered list of 'features' (i.e., terms) in our corpus. It includes (unless we explicitly define it) every word in the corpus, hence another reason to get rid of stop words early. These will also be the columns on the term-document matrix. 

In [14]:
index_vocabulary = {
    1: 'clever',
    2: 'handsome',
    3: 'loved',
    4: 'prince',
    5: 'princess',
    6: 'said'
}

In [15]:
index_vocabulary

{1: 'clever', 2: 'handsome', 3: 'loved', 4: 'prince', 5: 'princess', 6: 'said'}

## Turning documents into vectors

To turn a document into a vector, we simply need to count the number of time each term in the index vocabulary occurs in that document. Note that I need to strip out the punctuation and convert the words to lowercase. For the first document (sentence) in the corpus, we get:

In [16]:
import string

def count(document_list, term):
    doc = document_list.lower().translate(None, string.punctuation).split()
    match = [x for x in doc if x == term] 
    return len(match)

In [17]:
documents[0]

'The princess was clever'

In [18]:
m1 = [count(documents[0], x) for x in index_vocabulary.values()]
m1

[1, 0, 0, 0, 1, 0]

We can also represent this a bit more explicitly with a labelled dataframe.

In [19]:
from pandas import DataFrame
df = DataFrame(m1).T
df.columns = index_vocabulary.values()
df

clever  handsome  loved  prince  princess  said
0       1         0      0       0         1     0

In [32]:
import numpy as np
tf_matrix = np.array(tuple([count(d, x) for x in index_vocabulary.values()] for d in documents))
tf_matrix

array([[1, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 1, 0],
       [0, 1, 0, 2, 1, 1]])

In [21]:
DataFrame(np.array(tuple([count(d, x) for x in index_vocabulary.values()] for d in documents)),
          columns = index_vocabulary.values())

clever  handsome  loved  prince  princess  said
0       1         0      0       0         1     0
1       0         1      0       1         0     0
2       1         0      1       1         1     0
3       0         1      0       2         1     1

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
import operator
from pprint import pprint
vectorizer = CountVectorizer(stop_words = 'english')

vectorizer.fit_transform(documents)
sorted(vectorizer.vocabulary_.items(), key=operator.itemgetter(1))

[(u'clever', 0),
 (u'handsome', 1),
 (u'loved', 2),
 (u'prince', 3),
 (u'princess', 4),
 (u'said', 5)]

In [23]:
smatrix = vectorizer.transform(documents)
print smatrix

  (0, 0)	1
  (0, 4)	1
  (1, 1)	1
  (1, 3)	1
  (2, 0)	1
  (2, 2)	1
  (2, 3)	1
  (2, 4)	1
  (3, 1)	1
  (3, 3)	2
  (3, 4)	1
  (3, 5)	1


In [24]:
smatrix.todense()

matrix([[1, 0, 0, 0, 1, 0],
        [0, 1, 0, 1, 0, 0],
        [1, 0, 1, 1, 1, 0],
        [0, 1, 0, 2, 1, 1]])

In [25]:
DataFrame(smatrix.todense(), columns = index_vocabulary.values())

clever  handsome  loved  prince  princess  said
0       1         0      0       0         1     0
1       0         1      0       1         0     0
2       1         0      1       1         1     0
3       0         1      0       2         1     1

## Term frequency-inverse document frequency

You might have already noticed a problem with using the raw frequency of words to characterise our documents. If we have a look at the term frequencies of our Grimm's fairytale corpus, we can see that our top 20 is dominated by words like 'say', 'go' and 'come'. These words are likely to occur in a high frequency in pretty much all of the tales, and therefore don't help us identify the unique topics of specific stories. What we want to do is weight the terms within a story so that terms that  occur many times within a small number of documents have the highest weight, and those that occur within all documents have the lowest weight. We can then determine which terms are most characteristic of specific documents.

We can do this with something called the term frequency-inverse document frequency, or tf-idf. This is simply a multiplication of the term frequencies in our document with something called the inverse document frequency (idf). Let's first cover how to calculate the idf before we move on to weighting the terms in our matrix.

The idf is simply the number of documents in the corpus divided by 1 plus the number of documents where the term appears. As you can see in our examples above, it is pretty common to have a term frequency of 0, so adding 1 simply prevents us dividing by 0.

Let's calculate the idf for each of the terms in our example corpus.

In [162]:
# Create function to clean up the string and strip out punctuation and case
def split_docs(document):
    doc = document.lower().translate(None, string.punctuation).split()
    return doc

# Calculate total number of documents in corpus
total_docs = len(documents)

# Calculate 1 + document frequency for each term in our vocabulary
term_dfs = [1.0 + len([count for count in [split_docs(tale).count(term) for tale in documents] 
                       if count != 0]) for term in index_vocabulary.values()]

# Calculate each idf
idfs = [math.log(y) for y in [total_docs / x for x in term_dfs]]

# Print idfs with 
df = DataFrame(idfs).T
df.columns = index_vocabulary.values()
df

clever  handsome     loved  prince  princess      said
0  0.287682  0.287682  0.693147     0.0       0.0  0.693147

Great! We now have all of our idfs. We can now move on to calculating the tf-idf. What we need to do is to our term frequencies and the inverse document frequencies. In applied terms, what this means is that we multiply each term frequency in a document by its associated idf. Let's have a look at a practical example for our fourth sentence. Our term frequency vector for this document is:

In [175]:
tf_matrix[0]

array([1, 0, 0, 0, 1, 0])

And our idfs are:

In [170]:
idfs

[0.28768207245178085,
 0.28768207245178085,
 0.6931471805599453,
 0.0,
 0.0,
 0.6931471805599453]

So multiplying them together would look like:

$\begin{bmatrix}1\times0.29 & 0\times0.29 & 0\times0.69 & 0\times0.00 & 1\times0.00 & 0\times0.69 \end{bmatrix}$

which then simplifies to:

$\begin{bmatrix}0.29 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \end{bmatrix}$

Let's now automate this for every document in our corpus and again pop it into a DataFrame with the vocabulary terms as columns.

In [181]:
tf_idfs = [y * idfs for y in tf_matrix]
DataFrame(tf_idfs, columns = index_vocabulary.values())

clever  handsome     loved  prince  princess      said
0  0.287682  0.000000  0.000000     0.0       0.0  0.000000
1  0.000000  0.287682  0.000000     0.0       0.0  0.000000
2  0.287682  0.000000  0.693147     0.0       0.0  0.000000
3  0.000000  0.287682  0.000000     0.0       0.0  0.693147

## Vector normalisation

Raw term frequency can be misleading, as it weights towards very high occurrences of a term within a document, either because of keyword spamming or simply the length of the document. We can address this by normalising the vector. [Play with normalised and non-normalised vector for cosine similarity later and see how that looks.]

To normalise a vector, we simply need to change all of the values so that they add up to 1. To do this, we divide it by the length of the vector, or it's norm, and this norm can be calculated in a couple of ways. 

### L2-norm
In the diagram below, you can see that I've plotted the terms which have a non-zero frequency from the first matrix. You can I've plotted 'princess' on the x-axis, and 'clever' on the y-axis. As this document has a raw term frequency of 1 for each, we pop a point at (1, 1). If we draw a direct line between the origin and this point, how do we calculate the length of it? 

[graph 1 here - dot and line only]

Well, you might have noticed that when you draw lines between the origin and (0,1) and (1,0), this forms a right angle triangle. 

[graph 2 here - triangle]

We can now dust off our high school maths, and use Pythagoras's theorem to calculate the length of the vector. 

In [90]:
import math
l2_norm_0 = math.sqrt(sum([i ** 2 for i in tf_matrix[0]]))
print("The length of the vector is %0.3f.") % l2_norm_0

The length of the vector is 1.414.


This is known as the L2-norm, and can be generalised a vector of any length. For example, for the 4th document in our example set the L2-norm would be calculated as:

In [91]:
l2_norm_3 = math.sqrt(sum([i ** 2 for i in tf_matrix[3]]))
print("The length of the vector is %0.3f.") % l2_norm_3

The length of the vector is 2.646.


### L1-norm

[graph 3 here - dot and Manhattan distance only]
 
There is another way of calculating the distance between the origin and the point representing our term frequencies. Rather than taking the most direct path to the point (also known as the Euclidean distance), we can calculate what is called the Manhattan distance. This distance measure follows the most direct non-diagonal (like if a cab was trying to drive through Manhattan!), and is therefore simply the sum of all of its horizontal and vertical components. If we add up all of the lines in the graph above, you can see that it is 2, or in other words, just a sum of all of the term frequencies in the vector. Let's confirm this with our first vector.

In [77]:
l1_norm_0 = sum(tf_matrix[0])
print("The length of the vector is %d.") % l1_norm

The length of the vector is 2.


So how do we use these norms to normalise our vectors? Well, we simply divide our raw vector by our normalised vector. Easy peasy!

In the case of the L1-norm, you can see that the normalised vector adds up to 1.

In [80]:
tf_matrix[0] * 1.0 / l1_norm_0

array([ 0.5,  0. ,  0. ,  0. ,  0.5,  0. ])

In the case of the L2-norm, the *squared* results add to 1.

In [85]:
[tf**2 for tf in tf_matrix[0] * 1.0 / l2_norm_0]

[0.49999999999999989, 0.0, 0.0, 0.0, 0.49999999999999989, 0.0]

We can now add what we've learned about the tf-idf and vector normalisation together with the earlier work we did in Scikit-Learn. We'll first reuse the raw frequency matrix we created 

## BREAK

In [50]:
tfidf_nonorm = tf_matrix[0] * tfidf.idf_
tfidf_nonorm

array([ 1.51082562,  0.        ,  0.        ,  0.        ,  1.22314355,  0.        ])

In [54]:
# L2 norm
l2_norm = [i ** 2 for i in tfidf_nonorm]
[n / math.sqrt(sum(l2_norm)) for n in tfidf_nonorm]

[0.55261253035951696, 0.0, 0.0, 0.0, 0.44738746964048309, 0.0]

In [55]:
# L1 norm
[n / sum(tfidf_nonorm) for n in tfidf_nonorm]

[0.55261253035951696, 0.0, 0.0, 0.0, 0.44738746964048309, 0.0]

In [27]:
freq_term_matrix = vectorizer.transform(documents)
print freq_term_matrix.todense()

[[1 0 0 0 1 0]
 [0 1 0 1 0 0]
 [1 0 1 1 1 0]
 [0 1 0 2 1 1]]


In [96]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm = 'l2')
tfidf.fit(freq_term_matrix)

print "IDF:", tfidf.idf_

IDF: [ 1.51082562  1.51082562  1.91629073  1.22314355  1.22314355  1.91629073]


In [52]:
tfidf_matrix = tfidf.transform(freq_term_matrix)
print tfidf_matrix.todense()

[[ 0.55261253  0.          0.          0.          0.44738747  0.        ]
 [ 0.          0.55261253  0.          0.44738747  0.          0.        ]
 [ 0.25723171  0.          0.32626581  0.20825124  0.20825124  0.        ]
 [ 0.          0.21289588  0.          0.34471513  0.17235756  0.27003143]]


In [86]:
tf_norm = tf_matrix[0] * 1.0 / sum(tf_matrix[0])
tf_norm

array([ 0.5,  0. ,  0. ,  0. ,  0.5,  0. ])

In [87]:
tf_norm * tfidf.idf_

array([ 0.75541281,  0.        ,  0.        ,  0.        ,  0.61157178,  0.        ])

Check - do you apply the term frequency to the raw frequency vector before you multiply it by the idf?
Steps:
* Calculate raw frequency vectors
* Apply sublinear term frequency
* Multiply by idf
* Apply L2-normalisation